name: Build and deploy Node.js app to Azure Web App - iotserver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install and build frontend (React)
      - name: Install and build frontend
        run: |
          cd backend/frontend
          npm install
          npm run build

      # Install and build backend (Node.js)
      - name: Install and build backend
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present

      # Upload artifact (backend including frontend build)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7C890B923F154B91817A14759B16AAD3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1851D5FD1BBA4DBCBB0B230756572B5F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2451D567D26B40238A2952E7A7BDFD13 }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'iotserver'
          slot-name: 'Production'
          package: ./backend  # Deploy from backend folder
